version: "3.4"
services:
  postgres:
    image: postgres:14.5
    environment:
      container_name: "habr-pg-14"
      POSTGRES_DB: "mazitov_db"
      POSTGRES_USER: "mazitov_user"
      POSTGRES_PASSWORD: "mazitov_password"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/"
    restart: always
    volumes:
      - /opt/lab1/init_database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  jupyter:
    image: jupyter/minimal-notebook
    environment:
      JUPYTER_TOKEN: "mazitov"
      PROD_JUPYTERHUB_API_TOKEN: ${PROD_JUPYTERHUB_API_TOKEN}
    volumes:
      - /opt/lab1:/home/jovyan/work
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      
